from odoo import models, fields, api, _


class Arsden(models.Model):
    _inherit = "sale.order"

    radiologo = fields.Many2one('hr.employee', string='Radiólogo')
    total = fields.Float(string='total')
    sub_total = fields.Float(string='SubTotal')
    iva = fields.Float(string='Iva (16%)')
    comi_rad = fields.Float(string='comicion Radiologo')
    comi_res = fields.Float(string='comicion Reseccion')
    email = fields.Char(string='E-mail:')
    referido = fields.Char(string='Referido por Dr. Dra:')
    movil = fields.Char(string='Telefono:')
    email_dr = fields.Char(string='Email Dr.:')
    movil_dr = fields.Char(string='Telefono del Dr. Dra.:')
    descri = fields.Char(string='Descripcion')
    order_1 = fields.Selection([('periapi', 'Periapicales Aisladas')], string='Periapicales Aisladas de:')
    order_2 = fields.Selection([('peria', 'Periapicales Completo Cono Paralelo')], string = 'Periapicales Completo Cono Paralelo')
    order_3 = fields.Selection([('der', 'Derecha'), ('izq', 'Izquierda')], string='Radiografia Coronal', )
    order_4 = fields.Selection([('pano', 'Panoramica')], string='Panoramica')
    order_5 = fields.Selection([('atm', 'ATM')], string='ATM')
    order_6 = fields.Selection([('st', 'Sin Trazado')], string='Cefalica Lateral')
    order_7 = fields.Selection([('mn', 'MoNomera'), ('tb', 'Tejido Blando'), ('rk', 'Rickels'), ('ucv', 'UCV')], string="Cefalica Lateral Con Trazado:")
    order_8 = fields.Selection([('pos', 'Posterior-Anterior'), ('ant', 'Anterior-Posterior')], string = 'Cefalica')
    order_9 = fields.Selection([('car', 'Carpal')], string='Carpal')
    order_10 = fields.Selection([('extra', 'Extraorales'), ('into', 'Intraorales')], string='Fotografias Digitales')
    order_11 = fields.Selection([('estv', 'Estudio (Virina)'), ('tra', 'Trabajo')], string='Modelo')
    max = fields.Selection([('max', 'Maxilar Completo')], string='Maxilar Completo')
    mand = fields.Selection([('mand', 'mandibula')], string='Mandibula')
    her = fields.Selection([('her', 'Hermiarcada')], string='Hermiarcada')
    zep = fields.Selection([('zep', 'Zona Especifica')], string='Zona Especifica')
    descri2 = fields.Char(string='Zona Especifica')
    finalidad = fields.Char(string='Finalidad')

class ArsdenAccount(models.Model):
    _inherit = "account.move"

    radiologo = fields.Many2one('hr.employee', string='Radiólogo')
    total = fields.Float(string='total')
    sub_total = fields.Float(string='SubTotal')
    iva = fields.Float(string='Iva (16%)')
    comi_rad = fields.Float(string='comicion Radiologo')
    comi_res = fields.Float(string='comicion Reseccion')
    email = fields.Char(string='E-mail:')
    referido = fields.Char(string='Referido por Dr. Dra:')
    movil = fields.Char(string='Telefono:')
    email_dr = fields.Char(string='Email Dr.:')
    movil_dr = fields.Char(string='Telefono del Dr. Dra.:')
    descri = fields.Char(string='Descripcion')
    order_1 = fields.Selection([('periapi', 'Periapicales Aisladas')], string='Periapicales Aisladas de:')
    order_2 = fields.Selection([('peria', 'Periapicales Completo Cono Paralelo')], string = 'Periapicales Completo Cono Paralelo')
    order_3 = fields.Selection([('der', 'Derecha'), ('izq', 'Izquierda')], string='Radiografia Coronal', )
    order_4 = fields.Selection([('pano', 'Panoramica')], string='Panoramica')
    order_5 = fields.Selection([('atm', 'ATM')], string='ATM')
    order_6 = fields.Selection([('st', 'Sin Trazado')], string='Cefalica Lateral')
    order_7 = fields.Selection([('mn', 'MoNomera'), ('tb', 'Tejido Blando'), ('rk', 'Rickels'), ('ucv', 'UCV')], string="Cefalica Lateral Con Trazado:")
    order_8 = fields.Selection([('pos', 'Posterior-Anterior'), ('ant', 'Anterior-Posterior')], string = 'Cefalica')
    order_9 = fields.Selection([('car', 'Carpal')], string='Carpal')
    order_10 = fields.Selection([('extra', 'Extraorales'), ('into', 'Intraorales')], string='Fotografias Digitales')
    order_11 = fields.Selection([('estv', 'Estudio (Virina)'), ('tra', 'Trabajo')], string='Modelo')
    max = fields.Selection([('max', 'Maxilar Completo')], string='Maxilar Completo')
    mand = fields.Selection([('mand', 'mandibula')], string='Mandibula')
    her = fields.Selection([('her', 'Hermiarcada')], string='Hermiarcada')
    zep = fields.Selection([('zep', 'Zona Especifica')], string='Zona Especifica')
    descri2 = fields.Char(string='Zona Especifica')
    finalidad = fields.Char(string='Finalidad')